### ISSUE TITLE
Install doesn't work!!!!!!

### ISSUE THREAD

**Issue by rcasperson-jc** [jolly-good-toolbelt/sphinx_gherkindoc#1]
This repo is out and available to the public, but it is relying on installs from internal Rackspace dependencies, so after a `git clone`, `poetry install` fails.

```
[[tool.poetry.source]]
name = "artifactory" <--- HERE
url = "https://artifacts.rackspace.net/artifactory/api/pypi/pypi/simple/"  <--- HERE

[tool.poetry.dependencies]
python = "^3.6"
Sphinx = ">=1.3"
sphinx_rtd_theme = ">=0.3.1"
behave = ">=1.2.6"
qecommon_tools = ">=1.0.0" . <--- HERE
recommonmark = ">=0.4.0"
```

**Comment by brolewis** [comment]
@rcasperson-jc This was released prematurely and there are some pending PRs that need to get merged before this can be re-released cleanly. My apologies for the inconvenience and will let you know once this has been resolved.

**Comment by brolewis** [comment]
@rcasperson-jc The latest changes have been pushed to the repository. The documentation has been updated (https://jolly-good-toolbelt.github.io/sphinx_gherkindoc/) and it has been published to PyPI (https://pypi.org/project/sphinx-gherkindoc/). In addition, the internal project has been closed.

**Comment by rcasperson-jc** [comment]
Much excellence, thank you kind stranger!
