### ISSUE TITLE
Double spaces not allowed in steps

### ISSUE THREAD

**Issue by rbcasperson** [jolly-good-toolbelt/sphinx_gherkindoc#45]
If I have a step in a feature file like this:

```gherkin
Given here is my  step
```

I get an error like this:
```
/_docs_working/jc_step_glossary.rst:538:term not in glossary: here is my step
```

I did not look into why this is happening exactly, but inside `_docs_working/jc_step_glossary.rst` there is a the step linked as a term that matches `here is my  step` with the double space. So something that causes that error is ignoring the double space.

**Comment by rbcasperson** [comment]
I'll assign this to myself to look into it and fix it. Just in case it is something outside of this tool, I don't want anyone else wasting their time.

**Comment by dgou** [comment]
Interesting. I have accidentally included extra spaces in my Gherkin before, but I don't think I've ever gotten as far as building the docs before fixing them...

**Comment by dgou** [comment]
This is over a year old, so I am guessing @rbcasperson 's investigations were of the "nah, it's a bug not worth fixing".
I'm pretty sure it's a formatting issue with how rST handles spacing within the link mechanism. It might be solvable with quoting, but I'm also OK with "close this issue" until we have a need to support it.

**Comment by rcasperson-jc** [comment]
Yeah I don't remember looking into this or fixing it, but I have not come across it since originally reporting it. It may be fixed from other recent changes, or maybe not, but I have not problem closing this issue.

**Comment by dgou** [comment]
Closing as not worth enough ROI to pursue :-)
