### ISSUE TITLE
--parser pytest_bdd option is not working

### ISSUE THREAD

**Issue by majorzoltan80** [jolly-good-toolbelt/sphinx_gherkindoc#46]
Getting this error, whe using 3.6.0 version:

```bash
shpinx-gherkindoc <input_folder> <output_folder> --parser pytest_bdd

sphinx-gherkindoc: error: argument --parser: invalid choice: 'pytest_bdd' (choose from 'behave')
```

Based on documentation, we do have a pytest_bdd listed among the parsers, so what am I doing wrong?

**Comment by bradsbrown** [comment]
@majorzoltan80 Do you have `pytest_bdd` installed in the same virtualenv as `sphinx_gherkindoc`? The parser selection logic supports both `pytest_bdd` and `behave`, but `pytest_bdd` is not a listed requirement for the `sphinx_gherkindoc` package, and so is only available as a parser option if you already have it installed.

**Comment by dgou** [comment]
This looks to be a tooling configuration error, going to close this as stale.
